%setenv OMP_NUM_THREADS 1
mex -v -largeArrayDims...
       -I"/home/htan8/armadillo-4.400.1-install/usr/include" ...
       -L"/home/htan8/armadillo-4.400.1-install/usr/lib64" ...
       -larmadillo -lgfortran ... % for g++
       CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ...  
       mx_assemble_pseudo_adjoint_forces.cpp ...
       assemble_pseudo_adjoint_forces.cpp ...
       shape_function.cpp ...
       local_coord_2D.cpp ...
       regular_element_pseudo_adjoint_forces.cpp ...
       IGFEM_element_pseudo_adjoint_forces.cpp ...
       child_element_NDNBJ.cpp ...
       supg.cpp ...
       body_source_functions.cpp
      
        %CXXFLAGS="\$CXXFLAGS"
        %LDFLAGS="\$LDFLAGS -fopenmp "
        %CXX="g++-4.7"  LDXX="g++-4.7" GCC="/usr/bin/g++-4.7"...    
        %mex -v -larmadillo -lgfortran assemble_mx.cpp assemble.cpp  COMPFLAGS="/openmp $COMPFLAGS" % for microsoft visual c++ 
        %mex -v -larmadillo -lgfortran assemble_mx.cpp assemble.cpp  COMPFLAGS="/Qopenmp $COMPFLAGS" % for intel C++ compiler